### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by bekulio** [shamit6/backgammon#16]
Not working on Firefox 54.0 32bit, the UI looks like that:
![shubapp](https://user-images.githubusercontent.com/30531743/28743289-20c5ed84-744f-11e7-846c-02969abe54a4.JPG)

**Comment by shamit6** [comment]
Firefox needs more specified styles (:
Fixed and I will upload it soon

**Comment by shamit6** [comment]
new link

https://blooming-brushlands-40139.herokuapp.com
